Carrito/Controllers/DetalleController.cs
using Carrito.Models;
using Carrito.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Carrito.Controllers
{
    public class DetalleController : Controller
    {
        // GET: Detalle
        public ActionResult Index(int? id)
        {
            var model = new DetalleViewModel();

            using (var context = new Entities())
            {
                Producto producto = context.Productos.FirstOrDefault(x => x.Id == id);

                // Se puede reemplazar por un operadores explicitos, pero semana santa
                if (producto == null) return View(model);

                model.Nombre = producto.Nombre;
                model.Descuento = producto.Descuento;
                model.Detalle = producto.Detalle;
                model.PrecioUnitario = producto.PrecioUnitario;
                model.Id = producto.Id.ToString();
            }

            return View(model);
        }
        public ActionResult Agregar(int id)
        {
            using (Entities context = new Entities())
            {
                var producto = context.Productos.FirstOrDefault(x => x.Id == id);
                int idUsuario = Convert.ToInt16(Session["Usuario"]);
                Models.Carrito carrito = context.Carritos.Include(x => x.Productos).FirstOrDefault(x => x.Usuario.Id == idUsuario);

                // Si es la primera vez que se está comprando algo y por ende no tiene carrito asociado
                if (carrito == null)
                {

                    var usuario = context.Usuarios.FirstOrDefault(x => x.Id == idUsuario);
                    var productos = new List<Producto> { producto };

                    var nuevoCarrito = context.Carritos.Add(new Models.Carrito() { Usuario = usuario, Productos = productos });
                    nuevoCarrito.Productos.Add(producto);
                    context.SaveChanges();
                    return RedirectToAction("Index", "Carrito", new { id = nuevoCarrito.Id });
                }
                // Si ya tiene un carrito
                carrito.Productos.Add(producto);
                context.SaveChanges();
                return RedirectToAction("Index", "Carrito", new { id = carrito.Id });

            }

        }
    }
}

Carrito/Controllers/HomeController.cs
using Carrito.Models;
using Carrito.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Carrito.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            IndexViewModel viewModel;
            using (var ctx = new Entities())
            {
                viewModel = new IndexViewModel
                {
                    productos = ctx.Productos.ToList(),
                    cantidadEnCarrito = "0"
                };

            }            
            
            return View(viewModel);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Carrito/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Carrito/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Carrito/Views/Home/Index.cshtml
@model Carrito.ViewModel.IndexViewModel
@{
    ViewBag.Title = "Home Page";
}

<div id="hot">
    <div class="box">
        <div class="container">
            <div class="col-md-12">
                <h2>Popular esta semana</h2>
            </div>
        </div>
    </div>
</div>
<div id="advantages">
    <div class="container">
        <div class="same-height-row">
            @foreach (var producto in Model.productos)
            {
            <div class="col-sm-4">
                <div class="box same-height clickable">
                    <h3>@Html.ActionLink(producto.Nombre,"Index","Detalle",new { id = producto.Id }, null)</h3>
                    <p>@producto.PrecioUnitario</p>
                </div>
            </div>
            }
        </div>
    </div>
</div>