Carrito/Controllers/CarritoController.cs
using Carrito.Models;
using Carrito.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Carrito = Carrito.Models.Carrito;

namespace Carrito.Controllers
{
    public class CarritoController : Controller
    {
        // GET: Carrito
        public ActionResult Index(int id)
        {
            var entities = new Entities();

            // Decirle a EF que cargue la coleccion relacionada
            var carrito = entities.Carritos.Include(x => x.Productos).FirstOrDefault(x => x.Id == id);

            var model = new CarritoViewModel();

            if (carrito == null) { return RedirectToAction("Index", "Home"); }

            // Se puede simplificar con operadores de casteo
            var productos = carrito.Productos.Select(x => new ProductoViewModel
            {
                Id = x.Id,
                Descuento = x.Descuento,
                Nombre = x.Nombre,
                PrecioUnitario = x.PrecioUnitario,
                Total = x.PrecioUnitario * (1 - x.Descuento / 100)
            })
                .ToList();

            model.Productos = new List<ProductoViewModel>();
            model.Productos.AddRange(productos);
            model.CantidadEnCarrito = productos.Count().ToString();
            model.Total = productos.Sum(x => x.Total);
            model.Id = carrito.Id;

            return View(model);

        }

        public ActionResult Eliminar(int carritoId, int productoId)
        {
            using (var ctx = new Entities())
            {
                var carrito = ctx.Carritos.Include(x => x.Productos).FirstOrDefault(x => x.Id == carritoId);
                var producto = ctx.Productos.FirstOrDefault(x => x.Id == productoId);
                carrito?.Productos.Remove(producto);
                ctx.SaveChanges();
            }


            return RedirectToAction("Index",new {id = carritoId });
        }
    }
}

Carrito/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="robots" content="all,follow">
    <meta name="googlebot" content="index,follow,snippet,archive">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Obaju e-commerce template">
    <meta name="author" content="Ondrej Svestka | ondrejsvestka.cz">
    <meta name="keywords" content="">

    <title>
        Obaju : e-commerce template
    </title>

    <meta name="keywords" content="">

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100' rel='stylesheet' type='text/css'>

    <!-- Estilos -->
    @Styles.Render("~/Content/css/theme")

    <link rel="shortcut icon" href="favicon.png">



</head>
<body>
    <!-- Barra superior -->
    <div id="top">
        <div class="container">
            <div class="col-md-6 offer" data-animate="fadeInDown">  
            </div>
            <div class="col-md-6" data-animate="fadeInDown">
                <ul class="menu">
                    <li>
                        <a href="#" data-toggle="modal" data-target="#login-modal">Bienvenido, @Session["Nombre"]</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Fin de barra superior -->
    <!-- Barra de navegacion -->
    <div class="navbar navbar-default yamm" role="navigation" id="navbar">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand home" href="@Href("~/Home/Index")" data-animate-hover="bounce">
                    <img src="Content/Images/logo.png" alt="Obaju logo" class="hidden-xs">
                    <img src="Content/Images/logo-small.png" alt="Obaju logo" class="visible-xs"><span class="sr-only">Obaju - go to homepage</span>
                </a>
                <div class="navbar-buttons">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
                        <span class="sr-only">Toggle navigation</span>
                        <i class="fa fa-align-justify"></i>
                    </button>
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#search">
                        <span class="sr-only">Toggle search</span>
                        <i class="fa fa-search"></i>
                    </button>
                    @Html.ActionLink("Items in cart", "Index", "Carrito", new { id = Session["Usuario"] }, new { @class = "btn btn-default navbar-toggle" })
                    </a>
                </div>
            </div>
            <!--/.navbar-header -->

            <div class="navbar-collapse collapse" id="navigation">

                <ul class="nav navbar-nav navbar-left">
                    <li class="active">
                        <a href="@Href("~/Home/Index")">Home</a>
                    </li>
                </ul>
            </div>
            <!--/.nav-collapse -->

            <div class="navbar-buttons">

                <div class="navbar-collapse collapse right" id="basket-overview">
                    <a href="@Url.Action("Index","Carrito",new { Id = Session["Carrito"] })">
                    <i class="fa fa-shopping-cart"></i><span class="hidden-sm">Ver Carrito</span></a>
                </div>
                <!--/.nav-collapse -->

                <div class="navbar-collapse collapse right" id="search-not-mobile">
                    <button type="button" class="btn navbar-btn btn-primary" data-toggle="collapse" data-target="#search">
                        <span class="sr-only">Toggle search</span>
                        <i class="fa fa-search"></i>
                    </button>
                </div>

            </div>

            <div class="collapse clearfix" id="search">

                <form class="navbar-form" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="input-group-btn">

                            <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>

                        </span>
                    </div>
                </form>

            </div>
            <!--/.nav-collapse -->

        </div>
        <!-- /.container -->
    </div>
    <!-- Fin de Barra de navegacion-->

    <div id="all">
        <!-- Contenido -->

        @RenderBody()
        <!-- Fin de contenido-->
        <!-- Footer -->
        <div id="footer" data-animate="fadeInUp">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-6">
                        <h4>Pages</h4>

                        <ul>
                            <li>
                                <a href="text.html">About us</a>
                            </li>
                            <li>
                                <a href="text.html">Terms and conditions</a>
                            </li>
                            <li>
                                <a href="faq.html">FAQ</a>
                            </li>
                            <li>
                                <a href="contact.html">Contact us</a>
                            </li>
                        </ul>

                        <hr>

                        <h4>User section</h4>

                        <ul>
                            <li>
                                <a href="#" data-toggle="modal" data-target="#login-modal">Login</a>
                            </li>
                            <li>
                                <a href="register.html">Regiter</a>
                            </li>
                        </ul>

                        <hr class="hidden-md hidden-lg hidden-sm">

                    </div>
                    <!-- /.col-md-3 -->

                    <div class="col-md-3 col-sm-6">

                        <h4>Top categories</h4>

                        <h5>Men</h5>

                        <ul>
                            <li>
                                <a href="category.html">T-shirts</a>
                            </li>
                            <li>
                                <a href="category.html">Shirts</a>
                            </li>
                            <li>
                                <a href="category.html">Accessories</a>
                            </li>
                        </ul>

                        <h5>Ladies</h5>
                        <ul>
                            <li>
                                <a href="category.html">T-shirts</a>
                            </li>
                            <li>
                                <a href="category.html">Skirts</a>
                            </li>
                            <li>
                                <a href="category.html">Pants</a>
                            </li>
                            <li>
                                <a href="category.html">Accessories</a>
                            </li>
                        </ul>

                        <hr class="hidden-md hidden-lg">

                    </div>
                    <!-- /.col-md-3 -->

                    <div class="col-md-3 col-sm-6">

                        <h4>Where to find us</h4>

                        <p>
                            <strong>Obaju Ltd.</strong>
                            <br>13/25 New Avenue
                            <br>New Heaven
                            <br>45Y 73J
                            <br>England
                            <br>
                            <strong>Great Britain</strong>
                        </p>

                        <a href="contact.html">Go to contact page</a>

                        <hr class="hidden-md hidden-lg">

                    </div>
                    <!-- /.col-md-3 -->



                    <div class="col-md-3 col-sm-6">

                        <h4>Get the news</h4>

                        <p class="text-muted">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>

                        <form>
                            <div class="input-group">

                                <input type="text" class="form-control">

                                <span class="input-group-btn">

                                    <button class="btn btn-default" type="button">Subscribe!</button>

                                </span>

                            </div>
                            <!-- /input-group -->
                        </form>

                        <hr>

                        <h4>Stay in touch</h4>

                        <p class="social">
                            <a href="#" class="facebook external" data-animate-hover="shake"><i class="fa fa-facebook"></i></a>
                            <a href="#" class="twitter external" data-animate-hover="shake"><i class="fa fa-twitter"></i></a>
                            <a href="#" class="instagram external" data-animate-hover="shake"><i class="fa fa-instagram"></i></a>
                            <a href="#" class="gplus external" data-animate-hover="shake"><i class="fa fa-google-plus"></i></a>
                            <a href="#" class="email external" data-animate-hover="shake"><i class="fa fa-envelope"></i></a>
                        </p>


                    </div>
                    <!-- /.col-md-3 -->

                </div>
                <!-- /.row -->

            </div>
            <!-- /.container -->
        </div>
        <!-- Fin de footer -->
        <!-- copyright -->
        <div id="copyright">
            <div class="container">
                <div class="col-md-6">
                    <p class="pull-left">© 2016 Jamil Chioino.</p>

                </div>
                <div class="col-md-6">
                    <p class="pull-right">
                        Template by <a href="http://bootstrapious.com/e-commerce-templates">Bootstrap Ecommerce Templates</a> with support from <a href="http://kakusei.cz">Designové předměty</a>
                        <!-- Not removing these links is part of the licence conditions of the template. Thanks for understanding :) -->
                    </p>
                </div>
            </div>
        </div>
        <!-- Fin de copyright -->



    </div>

    <!-- Scripts -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/theme")

    <!-- Fin de Scripts-->



</body>

</html>